version: 0.2

phases:
  install:
    commands:
      - apt install -y zip
  build:
    commands:
      - zip -r sample.zip .
artifacts:
  files:
    - '**/*'
  name: build_output
  enable-symlinks: yes